CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "identifier" text UNIQUE PRIMARY KEY,
  "username" text,
  "group" text,
  "inventory_id" int,
  "avatar_url" text,
  "last_position" json,
  "created_at" bigint,
  "time_spent" int DEFAULT 0
);

CREATE TABLE "user_kits" (
  "identifier" text,
  "rank" text,
  "redeemed_at" int
);

CREATE TABLE "user_boosters" (
  "identifier" text,
  "kind" text,
  "expire_at" int
);

CREATE TABLE "user_skins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "identifier" text,
  "name" text,
  "skin" jsonb
);

CREATE TABLE "user_purchases" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "cfx_identifier" text,
  "product" text,
  "redeemed" bool
);

CREATE TABLE "inventories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "items" json
);

CREATE TABLE "bans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "expiring_at" INT NOT NULL,
  "reason" text,
  "identifiers" json
);

CREATE TABLE "user_kills" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "killer_identifier" text,
  "victim_identifier" text,
  "ranking" int,
  "killed_at" bigint
);

CREATE TABLE "user_ranks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "identifier" text,
  "rank" text,
  "expiring" bigint
);

CREATE TABLE "user_statistics" (
  "identifier" text UNIQUE,
  "duels_won" INT DEFAULT 0,
  "duels_lost" INT DEFAULT 0,
  "kills" INT DEFAULT 0,
  "deaths" INT DEFAULT 0,
  "ranking" INT DEFAULT 1000,
  "xp" INT DEFAULT 0,
  "visits" INT DEFAULT 0
);

CREATE TABLE "user_achievements" (
  "identifier" text UNIQUE,
  "achievement_id" int
);

CREATE TABLE "user_vehicles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_identifier" text,
  "model" text,
  "properties" jsonb
);

CREATE TABLE "user_lockers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_identifier" text,
  "name" text,
  "inventory_id" int
);

CREATE TABLE "gangs" (
  "name" text UNIQUE,
  "owner_identifier" text,
  "inventory_id" INT,
  "created_at" bigint,
  "upgrades" int DEFAULT 0,
  "ranking" int DEFAULT 0
);

CREATE TABLE "gang_members" (
  "gang_name" text,
  "identifier" text UNIQUE,
  "role" text
);

CREATE TABLE "gang_zones" (
  "name" text,
  "taken_by" text DEFAULT null,
  "taken_at" bigint,
  "position" jsonb
);

CREATE TABLE "gang_skins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "gang_name" text,
  "name" text,
  "skin" jsonb
);

CREATE TABLE "marketplace_products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehicle_id" INT,
  "price" INT
);

CREATE TABLE "marketplace_cache" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "identifier" text,
  "price" INT
);

CREATE INDEX ON "user_kits" ("identifier");

CREATE INDEX ON "user_skins" ("id");

CREATE INDEX ON "user_skins" ("identifier");

CREATE INDEX ON "inventories" ("id");

CREATE INDEX ON "user_kills" ("killer_identifier");

CREATE INDEX ON "user_kills" ("victim_identifier");

CREATE INDEX ON "user_ranks" ("identifier");

CREATE INDEX ON "user_statistics" ("identifier");

CREATE INDEX ON "user_vehicles" ("id");

CREATE INDEX ON "user_vehicles" ("owner_identifier");

CREATE INDEX ON "user_vehicles" ("model");

CREATE INDEX ON "user_lockers" ("owner_identifier");

CREATE INDEX ON "user_lockers" ("inventory_id");

CREATE INDEX ON "gangs" ("name");

CREATE INDEX ON "gangs" ("owner_identifier");

CREATE INDEX ON "gang_members" ("gang_name");

CREATE INDEX ON "gang_members" ("identifier");

CREATE INDEX ON "gang_zones" ("name");

CREATE INDEX ON "gang_zones" ("taken_by");

CREATE INDEX ON "gang_skins" ("gang_name");

CREATE INDEX ON "marketplace_products" ("id");

CREATE INDEX ON "marketplace_products" ("vehicle_id");

CREATE INDEX ON "marketplace_cache" ("id");

CREATE INDEX ON "marketplace_cache" ("identifier");

ALTER TABLE "users" ADD FOREIGN KEY ("inventory_id") REFERENCES "inventories" ("id");

ALTER TABLE "user_kits" ADD FOREIGN KEY ("identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_skins" ADD FOREIGN KEY ("identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_kills" ADD FOREIGN KEY ("killer_identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_kills" ADD FOREIGN KEY ("victim_identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_ranks" ADD FOREIGN KEY ("identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_statistics" ADD FOREIGN KEY ("identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_vehicles" ADD FOREIGN KEY ("owner_identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_lockers" ADD FOREIGN KEY ("owner_identifier") REFERENCES "users" ("identifier");

ALTER TABLE "user_lockers" ADD FOREIGN KEY ("inventory_id") REFERENCES "inventories" ("id");

ALTER TABLE "gangs" ADD FOREIGN KEY ("owner_identifier") REFERENCES "users" ("identifier");

ALTER TABLE "gangs" ADD FOREIGN KEY ("inventory_id") REFERENCES "inventories" ("id");

ALTER TABLE "gang_members" ADD FOREIGN KEY ("gang_name") REFERENCES "gangs" ("name");

ALTER TABLE "gang_members" ADD FOREIGN KEY ("identifier") REFERENCES "users" ("identifier");

ALTER TABLE "gang_zones" ADD FOREIGN KEY ("taken_by") REFERENCES "gangs" ("name");

ALTER TABLE "gang_skins" ADD FOREIGN KEY ("gang_name") REFERENCES "gangs" ("name");

ALTER TABLE "marketplace_products" ADD FOREIGN KEY ("vehicle_id") REFERENCES "user_vehicles" ("id");

ALTER TABLE "marketplace_cache" ADD FOREIGN KEY ("identifier") REFERENCES "users" ("identifier");
